{% set name = "starlette" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d12d22f22f859131f6e772f3a2a7a8c43fb3d27c72e06ecbbdbd48506ff835d4

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    # everything here below is in extras_require: 
    # move to an "optional requirements" field as 
    # soon as conda allows it
    - aiofiles
    - graphene
    - itsdangerous
    - jinja2
    - python-multipart
    - pyyaml
    - requests
    - ujson

test:
  commands:
    - python -c "from starlette import *"

about:
  home: https://www.starlette.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'The little ASGI framework that shines. ✨'
  description: |
    Starlette is a lightweight [ASGI](https://asgi.readthedocs.io/en/latest/)
    framework/toolkit.

    It is ideal for building high performance asyncio services, and supports
    both HTTP and WebSockets.
  doc_url: https://www.starlette.io/
  dev_url: https://github.com/encode/starlette/

extra:
  recipe-maintainers:
    - carlodri
