{% set name = "starlette" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}-recipe
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 05d0213193f2fbaae60e2ecb593b4add4262ad4e46536b54abe36f11a71724e0

build:
  number: 0
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - hatchling

outputs:
  - name: {{ name }}
    build:
      script: python -m pip install . --no-deps --no-build-isolation -vv
    requirements:
      host:
        - python
        - pip
        - hatchling
      run:
        - python
        - anyio >=3.6.2,<5
        - typing_extensions >=4.10.0  # [py<313]
    test:
      imports:
        - starlette
      requires:
        - pip
      commands:
        - pip check
  - name: {{ name }}-full
    build:
      script: echo Nothing to do.
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - {{ pin_subpackage('starlette', exact=True) }}
        - itsdangerous
        - jinja2
        - python-multipart >=0.0.18
        - pyyaml
        - httpx >=0.27.0,<0.29.0
        - httpx2 >=2.0.0
    test:
      source_files:
        - tests
      imports:
        - starlette
      requires:
        - pip
        - pytest >=8.4.0
        - sniffio
        # httpx adds "zstd" to Accept-Encoding when zstandard is importable
        - zstandard
        # https://github.com/Kludex/starlette/blob/0.52.1/docs/release-notes.md?plain=1#L9
        # typing-extensions is still needed for tests for all python versions
        - typing_extensions >=4.10.0  # [py>=313]
        - trio >=0.30.0
      commands:
        - pip check
        - python -c "from starlette import *"
        {% set deselect_tests = "" %}
        # > raise source.error("incomplete escape %s" % escape, len(escape))
        # E re.PatternError: incomplete escape \U at position 15
        {% set deselect_tests = deselect_tests + " --deselect=tests/test_config.py::test_missing_env_file_raises" %}  # [win]
        # E +  where 200 = <Response [200 OK]>.status_code
        {% set deselect_tests = deselect_tests + " --deselect=tests/test_staticfiles.py::test_staticfiles_with_invalid_dir_permissions_returns_401" %}  # [win]
        # E AttributeError: module 'os' has no attribute 'pathconf'
        {% set deselect_tests = deselect_tests + " --deselect=tests/test_staticfiles.py::test_staticfiles_filename_too_long" %}  # [win]
        - pytest -v tests {{ deselect_tests }}

about:
  home: https://www.starlette.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The little ASGI framework that shines
  description: |
    Starlette is a lightweight [ASGI](https://asgi.readthedocs.io/en/latest/) framework/toolkit.
    It is ideal for building high performance asyncio services, and supports
    both HTTP and WebSockets.
  doc_url: https://www.starlette.io
  dev_url: https://github.com/encode/starlette

extra:
  recipe-maintainers:
    - carlodri
    - dgasmith
