{% set name = "starlette" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}-recipe
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5268ef5d4904ec69582d5fd207b869a5aa0cd59529848ba4cf429b06e3ced99a

build:
  number: 0

outputs:
  - name: {{ name }}
    build:
      noarch: python
    script: build_base.sh
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
    test:
      commands:
        - python -c "from starlette import *"

  - name: {{ name }}-full
    build:
      noarch: python
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - {{ pin_subpackage('starlette', exact=True) }}
        - aiofiles
        - graphene
        - itsdangerous
        - jinja2
        - python-multipart
        - pyyaml
        - requests
        - ujson
    test:
      commands:
        - python -c "from starlette import *"

about:
  home: https://www.starlette.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The little ASGI framework that shines. ✨
  description: |
    Starlette is a lightweight [ASGI](https://asgi.readthedocs.io/en/latest/)
    framework/toolkit.

    It is ideal for building high performance asyncio services, and supports
    both HTTP and WebSockets.
  doc_url: https://www.starlette.io/
  dev_url: https://github.com/encode/starlette/

extra:
  recipe-maintainers:
    - carlodri
    - dgasmith
