{% set name = "starlette" %}
{% set version = "0.52.1" %}

package:
  name: {{ name|lower }}-recipe
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 834edd1b0a23167694292e94f597773bc3f89f362be6effee198165a35d62933

build:
  number: 0
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - hatchling

outputs:
  - name: {{ name }}
    build:
      script: python -m pip install . --no-deps --no-build-isolation -vv
    requirements:
      host:
        - python
        - pip
        - hatchling
      run:
        - python
        - anyio >=3.6.2,<5
        - typing_extensions >=4.10.0  # [py<313]
    test:
      imports:
        - starlette
      requires:
        - pip
      commands:
        - pip check
        
  - name: {{ name }}-full
    build:
      script: echo Nothing to do.
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - {{ pin_subpackage('starlette', exact=True) }}
        - itsdangerous
        - jinja2
        - python-multipart >=0.0.18
        - pyyaml
        - httpx >=0.27.0,<0.29.0
    test:
      source_files:
        - tests
      imports:
        - starlette
      requires:
        - pip
        - pytest >=8.4.0
        - sniffio
        # https://github.com/Kludex/starlette/blob/0.52.1/docs/release-notes.md?plain=1#L9
        # typing-extensions is still needed for tests for all python versions
        - typing_extensions >=4.10.0  # [py>=313]
        - trio >=0.30.0
      commands:
        - pip check
        - python -c "from starlette import *"
        - pytest -v tests

about:
  home: https://www.starlette.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The little ASGI framework that shines
  description: |
    Starlette is a lightweight [ASGI](https://asgi.readthedocs.io/en/latest/) framework/toolkit.
    It is ideal for building high performance asyncio services, and supports
    both HTTP and WebSockets.
  doc_url: https://www.starlette.io
  dev_url: https://github.com/encode/starlette

extra:
  recipe-maintainers:
    - carlodri
    - dgasmith
