{% set name = "starlette" %}
{% set version = "0.47.3" %}

package:
  name: {{ name|lower }}-recipe
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6bc94f839cc176c4858894f1f8908f0ab79dfec1a6b8402f6da9be26ebea52e9

build:
  number: 0
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - hatchling

outputs:
  - name: {{ name }}
    build:
      script: python -m pip install . --no-deps --no-build-isolation -vv
    requirements:
      host:
        - python
        - pip
        - hatchling
      run:
        - python
        - anyio >=3.6.2,<5
        - typing_extensions >=4.10.0  # [py<313]
    test:
      imports:
        - starlette
      requires:
        - pip
      commands:
        - pip check

  - name: {{ name }}-full
    build:
      script: echo Nothing to do.
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - {{ pin_subpackage('starlette', exact=True) }}
        - itsdangerous
        - jinja2
        - python-multipart >=0.0.18
        - pyyaml
        - httpx >=0.27.0,<0.29.0
    test:
      imports:
        - starlette
      requires:
        - pip
        - python
      commands:
        - pip check
        - python -c "from starlette import *"

about:
  home: https://www.starlette.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The little ASGI framework that shines
  description: |
    Starlette is a lightweight [ASGI](https://asgi.readthedocs.io/en/latest/) framework/toolkit.

    It is ideal for building high performance asyncio services, and supports
    both HTTP and WebSockets.
  doc_url: https://www.starlette.io/
  dev_url: https://github.com/encode/starlette/

extra:
  recipe-maintainers:
    - carlodri
    - dgasmith
