travis:
  secure:
    BINSTAR_TOKEN: QbyHqZqo/dwV+H1ziR9UqIdQAOzLYxBP7IcQQaBJfUIMx6vQ9Z3lulsRYp6jYs+E4Bjkc2FJ8Sk2/0GkY4uE3a93NlbTIDMLMMUumSh3Q2bE2oZ1RjvkFkHj+/vExVzA6/2Fd0Mmdu1mr7wjavm+ZEC1SWBj0UbVij9LRJYdkUKZCmBHF+v+rjI/YZAseW7+SkmaXzxsj76sZ6xDC6BIcpgNp6xS2HXkpNTakwSxlGaRKFWuRabbrSS72igmOaAAIEfWn14+0vzeErdnloaIu0wiwVsZigjAsSSM/J+QN8TIWi1Mn15weA4NCDNZN+7gQBCHIN8Nbunb05lxJ5v8rXW7DSle0c6rgBbGOuAMKdmXGgQ8FrzJ/70d7ZYieAs1comtGX4sautnzgD5EY61fHuIYIQY2DV1mFEEswtHoSqxWaQY+2l6UNDqd3FPoOBsT1LTZJb1csnTEkxvwzy/KZ+DBkTKFlvTTjEXKOEtBtjUpQmHtvDcsM/3L/6VZzngIL7NGXaP7D8ZF8l+aOsmF1PSikHb7M8W+u14Jl6i9pKu5vYSjAdg0WzGwQIg06jHJAwSbUsx/qdm+vob49uq5GkG7fcjHrYQl7IGZIOD2XR6EcUFtw9pbcsMSbIoACnXOdcjZQFznCYwrV9iuExgymva+XpfhvOruXptUZ/oqhY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
